version: '3'

services:
  web:
    build: .
    container_name: zimmerei-stark-homepage
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - NODE_ENV=production
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.stark.rule=Host(`stark.loacher.com`)"
      - "traefik.http.routers.stark.entrypoints=websecure"
      - "traefik.http.routers.stark.tls.certresolver=cloudflare"
      - "traefik.http.services.stark.loadbalancer.server.port=3000"

networks:
  proxy:
    external: true
